#!/usr/local/bin/bash

#Author: Srikanth Marni

#Date created: June 1 2022

#Last modified: June 1 2022

#Description: "This is the file which backups all the files in the ~/Desktop/dentin folder"

#Usage: Run the "~/Desktop/Bash-OP/backupscript" command when backup is required.
echo
echo "Hello, ${USER^^}"
echo "I will now backup your dentin directory, ~/Desktop/dentin/*"
Backuploc=~/Desktop/Bash-op/
currentdir=$(PWD)
file=~/Desktop/dentin/*
echo 
echo "You are running the script from $currentdir."
echo "I will store the backup file in ${Backuploc}."

tar -cvf ${Backuploc}/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ${file}
2>/dev/null
echo "Backup completed successfully!"
exit 0

